import React, { useState } from 'react';
import OsWindow from './OsWindow';
import MechButton from './MechButton';

export default function BilingualOutput({ en, hi }) {
  const [activeLang, setActiveLang] = useState('en');

  const content = activeLang === 'en' ? en : hi;
  const isHindiEmpty = activeLang === 'hi' && !hi;

  return (
    <OsWindow title="EXPLANATION_VIEWER.EXE">
      <div className="flex gap-4 mb-4 bg-retro-gray p-2 border-2 border-black">
        <label className="flex items-center gap-2 cursor-pointer">
          <input 
            type="radio" 
            name="lang" 
            value="en" 
            checked={activeLang === 'en'} 
            onChange={() => setActiveLang('en')}
            className="w-4 h-4"
          />
          <span className="font-mono font-bold text-black">ENGLISH</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input 
            type="radio" 
            name="lang" 
            value="hi" 
            checked={activeLang === 'hi'} 
            onChange={() => setActiveLang('hi')}
            className="w-4 h-4"
          />
          <span className="font-mono font-bold text-black">HINDI (हिंदी)</span>
        </label>
      </div>

      <div 
        key={activeLang}
        className="border-4 border-black bg-white p-4 min-h-[100px] font-mono text-sm leading-relaxed text-black shadow-mech"
      >
        {isHindiEmpty ? (
          <span className="text-gray-500 font-bold italic">HINDI OUTPUT UNAVAILABLE</span>
        ) : (
          <span>
            {content}
          </span>
        )}
      </div>

      <div className="border-t-2 border-black mt-4 pt-2 text-xs font-mono font-bold text-black flex justify-between">
        <span>GENERATED BY: ALGORITHMIC STRUCTURAL TEMPLATE ENGINE v2</span>
        <span className="bg-white border-2 border-black px-1">NO AI</span>
      </div>
    </OsWindow>
  );
}
